### ISSUE TITLE
Sraping on Hashtag (not user)

### ISSUE THREAD

**Issue by yarnball** [rarcega/instagram-scraper#14]
Hi,

Great work on this project.

I realise this might be outside the scope of your original intention, but would it be possible to scrape via the Hashtag instead of username?

It looks like the app.py is pulling the users media url with a parameter max_id, and the hashtag setup is probably different.

I've forked your repo and made an attempt to make the changes myself- but it keeps telling me "User <blah> does not exist". 

My fork:
https://github.com/yarnball/instagram-scraper

Thanks

**Comment by rarcega** [comment]
This should be feasible. I haven't had the chance to dive deeper into this, but you'll need to use a different url. If you examine the network requests, you'll notice that a POST request is being is made to https://www.instagram.com/query. As an example, the following form data is sent in the request when searching for the tag *instagram*:

```
q:ig_hashtag(instagram) { media.after(J0HV75S-wAAAF0HV75S9AAAAFiYA, 6) {
  count,
  nodes {
    caption,
    code,
    comments {
      count
    },
    comments_disabled,
    date,
    dimensions {
      height,
      width
    },
    display_src,
    id,
    is_video,
    likes {
      count
    },
    owner {
      id
    },
    thumbnail_src,
    video_views
  },
  page_info
}
 }
ref:tags::show
```

So it looks like in the request you must define the hash tag, from which media (based off some id) to start searching from, and the fields to return in the response.

**Comment by sruteesh** [comment]
Any updates?

**Comment by astreinerBaum** [comment]
I would be interested in that, too.
Can't really wrap my head around the code. 
Would it not be working if I change the URL?

**Comment by xTEddie** [comment]
Hi, is there any updates on this feature? I would be very interested

**Comment by rarcega** [comment]
I am in the process of researching this. Stay tuned.

**Comment by xTEddie** [comment]
I found a hashtag scraper written in ruby: https://github.com/dannyvassallo/insta_scrape 
PhamtonJS, a web browser automation tool was used to scrap this. The url https://www.instagram.com/explore/tags/[hashtag] was used.

**Comment by seanpatel** [comment]
Hi, 

Please can you [look at this commit](https://github.com/Thammus/instaloader/commit/3e1360160dacf89852a4cf4d3dae8425401b6409)? It implements hashtag download in python. 

I wasn't able to get that library to work with it's latest commit. Not a python guy :( 

Thanks!!!

**Comment by rarcega** [comment]
I should have this functionality implemented by the end of week (hopefully).

**Comment by yarnball** [comment]
Teriffic. Thank you

**Comment by seanpatel** [comment]
@yarnball Please fix the typo in the issue title. It's pretty glaring, and reads like "r*ping". Not good. Thank you and I'll delete this msg once you fix it.

**Comment by seanpatel** [comment]
Hi Richard,

Thank you for this incredible feature. I really really absolutely love it! Doing research for a social media project and this will help sooooo much!

Also kudos to other authors incl. Mr Gaurav! You all have done a great job on this challenging work.

I noticed 1 thing. I tried tag download for kicks on **#boxingmeme** . The [tag page shows **5,292 posts**](https://www.instagram.com/explore/tags/boxingmeme/) as of today **13th May of 2017**. 

I ran the scraper, and it stopped after downloading **3,330 posts**. Here's the console output. 

```
$ instagram-scraper boxingmeme --tag --media_metadata
Searching #boxingmeme for posts: 3330 media [02:41,  6.59 media/s]
Downloading: 100%|##########| 3330/3330 [00:02<00:00, 1490.97it/s]
```

No errors. But it stopped at **3330 posts**, instead of going all the way to **5292 posts**.

The last media items, and also the oldest I suppose, at #3330 was this post.... https://www.instagram.com/p/O9dXZHsG6G/ it's dated "1346347009" unix date? converts to "Thu, 30 Aug 2012 17:16:49 GMT". So goes back 5 years. Not bad. 

Not a big deal. Thought I should let you gentlemen know. Is perhaps IG web viewer going only that far back ( 5 years)? 

[Another scraper didn't go this far](https://github.com/Thammus/instaloader/issues/20#issuecomment-296378505). It stopped way before at like **336 posts only**. I have notified that gentleman also. Maybe you all can collaborate.

Once again, excellent job on this gentlemen!!!

**Comment by rarcega** [comment]
@seanpatel I verified that the web interface is displaying same amount of posts and the last post is the same one that you mentioned. The posts count includes ones that are posted under private accounts which is most likely the cause for the discrepancy.

**Comment by seanpatel** [comment]
> The posts count on the explore/tags page includes ones that are posted under private accounts (and are not visible publicly)

I never thought of that. Makes sense. Thanks for looking into this. Really appreciate the stellar work!

**Comment by caliohr** [comment]
I don't know if this thread is still active but i'll try anyways. Does any other information come with the pictures, such as other hashtags provided with the post and geotag?
