### ISSUE TITLE
Rookie Error Help

### ISSUE THREAD

**Issue by EternalYZY** [rarcega/instagram-scraper#56]
Hi, i've downloaded this along with Python(haven't used Python for ages).

I've installed Pip(I think), but I cannot get the script running at all.

I'm being stupid I know, but this will be perfect for a project and if someone could assist with setup or tell me where i'm going wrong it would be great!
image below of what i'm trying
[http://i.imgur.com/jUzI7kK.png](url)

**Comment by EternalYZY** [comment]
Or if I try running app.py
[http://i.imgur.com/lfhSB8X.png](url)
And when I run setup.py
[http://i.imgur.com/O9YjGbf.png](url)

**Comment by rarcega** [comment]
@EternalYZY Thanks for your interest in instagram-scraper! You're running the commands in the interactive python shell which is not correct. If you're on windows, you should run the commands at the command prompt.

Since you have Python v3.6 installed, pip should be available at command prompt. You can run the following command to install the app:

```cmd
C:\> pip install instagram-scraper
```

Once installed, you can simply run it like so (see the README for more options):
```cmd
C:\> instagram-scraper therock
```
which will scrape the instagram user `therock` for posts and download them to the current worker directory/therock.

Hope that helps.
