### ISSUE TITLE
I tried to download a user, and the script crashed with an error dump that filled the terminal.

### ISSUE THREAD

**Issue by Rich700000000000** [rarcega/instagram-scraper#7]
I downloaded the newest version a few minutes ago, and tried to download an instagram. 

It worked, and then it printed this:

`Downloading:   0%|                                                                                                                          | 0/464 [00:00<?, ?it/s]'{u\'alt_media_url\': u\'https://scontent-ord1-1.cdninstagram.com/t50.2886-16/13477837_506697689519627_1722745634_n.mp4\',\n u\'can_delete_comments\': False,\n u\'can_view_comments\': True,\n u\'caption\': {u\'created_time\': u\'1466362113\',\n              u\'from\': {u\'full_name\': u\'Wright\',\n                        u\'id\': u\'143862950\',\n                        u\'profile_picture\': u\'https://scontent-ord1-1.cdninstagram.com/t51.2885-19/1889238_802261243224897_1527459696_a.jpg\',\n                        u\'username\': u\'hotwrightnow\'},\n              u\'id\': u\'17849420611083698\',\n              u\'text\': u"I\'m`

And contiuned on for 30 more lines, the rest is here: http://pastebin.com/VKAAXCBz

What exactly happened?

**Comment by rarcega** [comment]
Thanks. I've identified the root cause of the problem. The exception is:
`[Errno 17] File exists`
which occurs when the save directory is being created but it already exists. This issue manifests because there is a race condition where multiple threads are simultaneously detecting the save directory as not existing and then try to create it. The first thread that creates it is successful however the rest fail because it already exists. 

This also explains the previous error from issue #3  `KeyError: 'url'`. When the File Exists error happens, the script never reaches the proceeding lines and never sets the `url` property. As a result, the exception handler fails when it tries to print the `url` property.

Please pull the latest update and let me know if you still experience this issue.
